---
name: Publish to Ansible Galaxy
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: pip3 install ansible-core

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Find collection artifact
        id: find_artifact
        run: echo "::set-output name=path::$(find . -name 'steam_cli_*.tar.gz')"

      - name: Publish collection
        env:
          GALAXY_API_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
        run: ansible-galaxy collection publish --token $GALAXY_API_TOKEN ${{ steps.find_artifact.outputs.path }}
